language: android
sudo: false
jdk: oraclejdk7

addons:
  apt-packages:
    - pandoc

cache:
  directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew test --continue

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - pandoc app/build/reports/tests/debug/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
